"""empty message

Revision ID: 00da6675c1e2
Revises: ff774cb935e0
Create Date: 2024-11-12 10:06:51.282144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00da6675c1e2'
down_revision = 'ff774cb935e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_meals', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
