"""empty message

Revision ID: 11b51c718f7b
Revises: c08294561c2f
Create Date: 2024-10-07 16:46:27.722429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b51c718f7b'
down_revision = 'c08294561c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_meals', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['recipe_id', 'schedule_id', 'day_of_week'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_meals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
