"""empty message

Revision ID: 2a2cd70a375b
Revises: 08faa3ea8ebb
Create Date: 2024-11-15 14:18:27.057866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2cd70a375b'
down_revision = '08faa3ea8ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_meals', schema=None) as batch_op:
        batch_op.drop_constraint('day-meals', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_meals', schema=None) as batch_op:
        batch_op.create_unique_constraint('day-meals', ['recipe_id', 'day_of_week'])

    # ### end Alembic commands ###
