"""empty message

Revision ID: 31f7d7ebb73d
Revises: 5ef204af7973
Create Date: 2024-09-23 11:28:56.731869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f7d7ebb73d'
down_revision = '5ef204af7973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('is_fav')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fav', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
